tensor = "torch.DoubleTensor"#"torch.cuda.DoubleTensor"#

task = "Pendulum-v0"#"MountainCarContinuous-v0"#"Reacher_Linux_20/Reacher.x86_64"#_20
total_simulations = 20#1#

cross_exp_size = 5000 # heat map buffer (20*100) * eps

max_reward_val = +1000
min_reward_val = -1000

