#####################################
# Most common to tune
#####################################

ddpg = true#false#
gae = true#false#

n_step = 1#5
batch_size = 256#16#24
discount_rate = 0.995
n_simulations = 3#20#12#

send_exp_delta = 10
critic_learn_delta = 80
fast_exp_epochs = 20
full_replay_count = 40

lr_actor = 1e-3
lr_critic = 1e-4

mcts_rounds = 3

max_n_episode = 300#1000# # 300 is only for mcar we want to do it faster
max_ep_draw_count = 40

detached_actor = true#false#

#####################################
# neural nets settings
#####################################

history_count = 4
history_features = 64

# for acrot we turning this on
her_state_size = 0#1#
her_state_features = 0#64#

#####################################
# PG algorithm settings
#####################################

postpone_exploring_while_learning = 3 # in terms of seconds ..

ppo_eps = 2e-1
loss_min = 1000

gae_tau = 0.95

#####################################
# replay buffer
#####################################

replay_size = 10000

her_max_ratio = 3

replay_reanalyze = true#false#
replay_cleaning = false#true#
prob_treshold = 3.0

replay_alpha = 0.7
replay_beta_iters = 10000
replay_beta_base = 0.3
replay_beta_top = 0.9

#####################################
# Quirks ~ related to gradients +-
#####################################

pg_mean = true#false#
action_repeat = 1#3#

good_reach = 1
advantages_enabled = true#false#
advantages_boost = true#false#
normalize_advantages = false#true#

attention_enabled = true#false#
attention_hidden = 64
attention_amplifier = 2.0

mcts_random_cap = 1000000

# temporary flag just for replay buffer
use_curiosity_buf = false#true#

#####################################
# Learning rates hyper params
#####################################

actor_update_delay = 3#1#
critic_update_delay = 4#1#

tau_base = 5e-3 # update from full episodes
tau_final = 3e-2
tau_replay_counter = 10000

#####################################
# debug and visuals
#####################################

max_n_step = 1#-10000#

dbgout_train = true#false#
dbgout_ratio = false#true#
dbgout = true#false#
loss_debug = false#true

#####################################
# MODEL specifics
#####################################

device = "cpu"#"cuda"#
tensor = "torch.DoubleTensor"#"torch.cuda.DoubleTensor"#
model_path = "reacher_sig_dtb"
load = false#true#
save = false#true#
