#####################################
# Most common to tune
#####################################

ddpg = true#false#
gae = false#true#

n_step = 3#1#
batch_size = 32#128#24#16#
select_count = 10
discount_rate = 0.99
n_simulations = 1#20#12#

send_exp_delta = 5
critic_learn_delta = 10
fast_exp_epochs = 5
full_replay_count = 30

lr_actor = 7e-4
lr_critic = 1e-3

mcts_rounds = 1

max_n_episode = 300#1000# # 300 is only for mcar we want to do it faster
max_ep_draw_count = 20

detached_actor = false#true#

freeze_delta = 2
freeze_count = 4

#####################################
# neural nets settings
#####################################

history_count = 2
rnn_n_layers = 2
full_rnn_out = false#true#
history_features = 256#512#

# for acrobot we turning this on
her_state_size = 0#1
her_state_features = 0#64

#####################################
# PG algorithm settings
#####################################

postpone_exploring_while_learning = 2 # in terms of seconds ..

ppo_eps = 2e-1
loss_min = 1000

gae_tau = 0.95

#####################################
# replay buffer
#####################################

replay_size = 10000

her_max_ratio = 3

replay_reanalyze = true#false#
replay_cleaning = false#true#
prob_treshold = 3.0

replay_alpha = 0.7
replay_beta_iters = 10000
replay_beta_base = 0.3
replay_beta_top = 0.9

#####################################
# Quirks ~ related to gradients +-
#####################################

pg_mean = true#false#
action_repeat = 1#3#

good_reach = 1
advantages_enabled = true#false#
advantages_boost = false#true#
normalize_advantages = false#true#

attention_enabled = false#true#
attention_hidden = 64
attention_amplifier = 2.0

mcts_random_cap = 1000000

# temporary flag just for replay buffer
use_curiosity_buf = true#false#

#####################################
# Learning rates hyper params
#####################################

actor_update_delay = 3#3#
critic_update_delay = 3#4#

tau_base = 1e-3 # update from full episodes
tau_final = 1e-3
tau_replay_counter = 100000

#####################################
# debug and visuals
#####################################

max_n_step = -10000#1#

dbgout_train = true#false#
dbgout_ratio = false#true#
dbgout = true#false#
loss_debug = false#true

#####################################
# MODEL specifics
#####################################

device = "cpu"#"cuda"#
tensor = "torch.DoubleTensor"#"torch.cuda.DoubleTensor"#
model_path = "reacher_sig_dtb"
load = false#true#
save = false#true#
