#####################################
# Most common to tune
#####################################

ddpg = true#false#
gae = false#true#

n_step = 5
batch_size = 24
discount_rate = 0.995
n_simulations = 1#20#12#
n_critics = 1
disjoint_critics = false#true#

critic_learn_delta = 40

lr_actor = 1e-4
lr_critic = 3e-4

mcts_rounds = 3

max_n_episode = 2000#300# # 300 is only for mcar we want to do it faster
max_ep_draw_count = 20

#####################################
# neural nets settings
#####################################

use_batch_norm = false#true#
use_curiosity_buf = false#true#

history_count = 3
history_features = 64

# for acrot we turning this on
her_state_size = 1#0#
her_state_features = 64#0#

#####################################
# PG algorithm settings
#####################################

fast_exp_epochs = 7
ppo_eps = 2e-1
loss_min = 1000

gae_tau = 0.95

#####################################
# replay buffer
#####################################

replay_size = 10000

her_max_ratio = 5

replay_reanalyze = true#false#
replay_cleaning = false#true#
prob_treshold = 3.0

replay_alpha = 0.7
replay_beta_iters = 10000
replay_beta_base = 0.3
replay_beta_top = 0.9

#####################################
# Quirks ~ related to gradients +-
#####################################

pg_mean = true#false#
action_repeat = 1#2#

good_reach = 1
advantages_enabled = true#false#
advantages_boost = true#false#
normalize_advantages = false#true#

attention_enabled = false#true#
attention_hidden = 64
attention_amplifier = 2.0

# reinforce or TD-lambda
td_lambda_replay_count = 6#10#
reinforce_clip = false
tau_clip = 0

mcts_random_cap = 1000000

#####################################
# Learning rates hyper params
#####################################

actor_update_delay = 4#3#1#
critic_update_delay = 5#3#1#

tau_base = 5e-2 # update from full episodes
tau_final = 3e-2
#tau_base = 5e-1
#tau_final = 7e-3
tau_replay_counter = 10000

#####################################
# debug and visuals
#####################################

max_n_step = -10000#1#

dbgout_train = true#false#
dbgout_ratio = false#true#
dbgout = true#false#
loss_debug = false#true

#####################################
# MODEL specifics
#####################################

device = "cpu"#"cuda"#
tensor = "torch.DoubleTensor"#"torch.cuda.DoubleTensor"#
model_path = "reacher_sig_dtb"
load = false#true#
save = false#true#
