device = "cpu"#"cuda"#
tensor = "torch.DoubleTensor"#"torch.cuda.DoubleTensor"#
model_path = "reacher_dtb"
load = false#true#
save = false#true#
dbgout = true#false#
loss_debug = false#true

n_step = 1
n_critics = 1
batch_size = 1 # contains whole subset of batches, therefore up to 50 * this numero ..
discount_rate = 0.995
disjoint_critics = false#true#

task = "/home/xxx/unity/Reacher_Linux_20/Reacher.x86_64"#
task_required_simulations = 20
n_simulations = 8
action_repeat = 1
max_reward_val = +1000
min_reward_val = -1000
replay_size = 10000 # we want to store those
cross_exp_size = 0
max_n_episode = 100
mcts_random_cap = 1000000
mcts_rounds = 2
max_ep_draw_count = 1

# reinforce or TD-lambda
td_lambda_replay_count = 0
reinforce_clip = false
tau_clip = 0

lr_actor = 3e-4
lr_critic = 1e-4

tau_base = 5e-1 # update from full episodes
tau_final = 1e-2
tau_replay_counter = 100000
actor_update_delay = 1# soft update of actor ~ off-policy, how much fits on explorer before
critic_update_delay = 1#40 # soft update of critic ~ off-policy, how much fits on explorer before
critic_learn_delta = 20 # here how much episodes before critic(and therefore also actor)-explorer update

# usually when we normalize advantages, we want to use sum in PG, and also attention is preferred
pg_mean = true#false#

good_reach = 1 # select from experience only related things if task is designed that way
advantages_enabled = true#false#
advantages_boost = false#true#
normalize_advantages = false#true#

attention_enabled = false#true#
attention_hidden = 64
attention_amplifier = 2.0

max_n_step = 1#-10000#

# scheduling of replay buffer randomnes
replay_alpha = 1.0
replay_beta_iters = 6000 # here we should have enough experience to do serious prioritzation
replay_beta_base = 0.2
replay_beta_top = 0.8
replay_prio_eps = 1e-16

#####################################
# neural nets settings
#####################################

#lstm advancement
history_count = 3
history_features = 128

her_state_size = 3
her_state_features = 32
her_max_ratio = 5

dbgout_train = true#false#
fast_exp_epochs = 6
ppo_eps = 2e-1
loss_min = 1000

dbgout_ratio = true#false#
ddpg = false#true#

replay_cleaning = true#false#
prob_treshold = 3.0

gae = true#false#
gae_tau = 0.95

replay_reanalyze = false#true#
