#####################################
# Most common to tune
#####################################

ddpg = false#true#
gae = true#false#

n_step = 1
batch_size = 12
select_count = 2
discount_rate = 0.99
n_simulations = 8

send_exp_delta = 10
critic_learn_delta = 10
fast_exp_epochs = 5
full_replay_count = 3

lr_actor = 9e-4
lr_critic = 1e-3

mcts_rounds = 1

max_n_episode = 30
max_ep_draw_count = 10

detached_actor = true#false#

freeze_delta = 0
freeze_count = 0

#####################################
# neural nets settings
#####################################

history_count = 1
rnn_n_layers = 2
full_rnn_out = false#true#
history_features = 256#512#

# for acrobot we turning this on
her_state_size = 3
her_state_features = 32

#####################################
# PG algorithm settings
#####################################

postpone_exploring_while_learning = 6 # in terms of seconds ..

ppo_eps = 2e-1
loss_min = 1000

gae_tau = 0.95

#####################################
# replay buffer
#####################################

replay_size = 670

her_max_ratio = 3

replay_reanalyze = true#false#
replay_cleaning = false#true#
prob_treshold = 3.0

replay_alpha = 0.7
replay_beta_iters = 10000
replay_beta_base = 0.3
replay_beta_top = 0.9

#####################################
# Quirks ~ related to gradients +-
#####################################

pg_mean = true#false#
action_repeat = 1#3#

good_reach = 1
advantages_enabled = true#false#
advantages_boost = true#false#
normalize_advantages = false#true#

attention_enabled = false#true#
attention_hidden = 64
attention_amplifier = 2.0

mcts_random_cap = 1000000

# temporary flag just for replay buffer
use_curiosity_buf = true#false#

#####################################
# Learning rates hyper params
#####################################

actor_update_delay = 5
critic_update_delay = 7

tau_base = 1e-3 # update from full episodes
tau_final = 5e-3
tau_replay_counter = 100000

#####################################
# debug and visuals
#####################################

max_n_step = -10000#1#

dbgout_train = true#false#
dbgout_ratio = false#true#
dbgout = true#false#
loss_debug = false#true

#####################################
# MODEL specifics
#####################################

device = "cpu"#"cuda"#
tensor = "torch.DoubleTensor"#"torch.cuda.DoubleTensor"#
model_path = "experimental"
load = true#false#
save = true#false#
