#####################################
# Most common to tune
#####################################

ddpg = true#false#
gae = false#true#

n_step = 5
batch_size = 16
discount_rate = 0.995
n_simulations = 1#20#12#
n_critics = 1
disjoint_critics = false#true#

critic_learn_delta = 7

lr_actor = 3e-4
lr_critic = 1e-4

mcts_rounds = 4

max_n_episode = 100#70#400#2000#
max_ep_draw_count = 8

#####################################
# neural nets settings
#####################################

use_batch_norm = true#false#

history_count = 3
history_features = 128

her_state_size = 0#3
her_state_features = 0#32

#####################################
# PG algorithm settings
#####################################

postpone_exploring_while_learning = true#false#
fast_exp_epochs = 4
ppo_eps = 2e-1
loss_min = 1000

gae_tau = 0.95

#####################################
# replay buffer
#####################################

replay_size = 10000

her_max_ratio = 5

replay_reanalyze = true#false#
replay_cleaning = false#true#
prob_treshold = 3.0

replay_alpha = 0.7
replay_beta_iters = 6000
replay_beta_base = 0.2
replay_beta_top = 0.8
replay_prio_eps = 1e-16

#####################################
# Quirks ~ related to gradients +-
#####################################

pg_mean = true#false#
action_repeat = 1#2#

good_reach = 1
advantages_enabled = true#false#
advantages_boost = true#false#
normalize_advantages = false#true#

attention_enabled = false#true#
attention_hidden = 64
attention_amplifier = 2.0

# reinforce or TD-lambda
td_lambda_replay_count = 10
reinforce_clip = false
tau_clip = 0

mcts_random_cap = 1000000

#####################################
# Learning rates hyper params
#####################################

actor_update_delay = 3
critic_update_delay = 3

tau_base = 5e-2
tau_final = 1e-3
tau_replay_counter = 1000000

#####################################
# debug and visuals
#####################################

max_n_step = 1#-10000#

dbgout_train = true#false#
dbgout_ratio = false#true#
dbgout = false#true#
loss_debug = false#true

#####################################
# MODEL specifics
#####################################

device = "cpu"#"cuda"#
tensor = "torch.DoubleTensor"#"torch.cuda.DoubleTensor"#
model_path = "reacher_sig_dtb"
load = true#false#
save = true#false#
