device = "cpu"#"cuda"#
tensor = "torch.DoubleTensor"#"torch.cuda.DoubleTensor"#
model_path = "models_dtb"
load = false
save = false
dbgout = true#false#
loss_debug = false#true

n_step = 3
n_critics = 1
batch_size = 4
discount_rate = 0.995
disjoint_critics = true#false#

task = "MountainCarContinuous-v0"
n_simulations = 1
action_repeat = 1
max_reward_val = +300
min_reward_val = -300
replay_size = 50000
max_n_eps = 1000
max_ep_draw_count = 100

mcts_rounds = 1
mcts_random_cap = 1000000
td_lambda_replay_count = 20

reinforce_clip = false
tau_clip = 0

lr_actor = 1e-3
lr_critic = 1e-4

tau_base = 1e-2
tau_final = 9e-3
tau_replay_counter = 10000
tau_adapt = 1e-3
actor_update_delay = 1
critic_update_delay = 1
critic_learn_delta = 1

pg_mean = true#false#

good_reach = 2
advantages_enabled = true#false#
advantages_boost = true#false#
normalize_advantages = false#true#

attention_enabled = false#true#
attention_hidden = 24
attention_amplifier = 1.0

max_n_step = -10000#1#

replay_alpha = 0.0
replay_beta_iters = 6000
replay_beta_base = 0.2
replay_beta_top = 0.7
replay_prio_eps = 1e-3

#####################################
# neural nets settings
#####################################

#lstm advancement
history_count = 2
history_features = 64

her_state_size = 0
her_state_features = 0
her_max_ratio = 0


