device = "cpu"#"cuda"#
tensor = "torch.DoubleTensor"#"torch.cuda.DoubleTensor"#
model_path = "models_dtb"
load = false
save = false
dbgout=true
loss_debug = false#true

n_step = 4              # reduce variance, how many rewards we take into account at critic predictions, but increasing bias a little by little
n_critics = 1           # how many critics we want per task, must be < than n_step ( temporary limitation ~ lazyness )
batch_size = 16         # for one critic! therefore real full batch = batch_size * n_critics * n_simulations(this is given by task)
discount_rate = 0.97   # rewards discount factor
disjoint_critics = false#true#

task = "Pendulum-v0"
n_simulations = 1
action_repeat = 1
max_reward_val = +100
min_reward_val = -200
replay_size = 100000
max_n_eps = 200
max_ep_draw_count = 40
mcts_rounds = 3
mcts_random_cap = 1000000
td_lambda_replay_count = 10

reinforce_clip = false
tau_clip = 0

lr_actor = 1e-3
lr_critic = 1e-4

tau_base = 1e-2 # update from full episodes
tau_final = 7e-3
tau_replay_counter = 100000
tau_adapt = 1e-3 # update from active experiences ~ we want to have it lower generaly
actor_update_delay = 4 # soft update of actor ~ off-policy, how much fits on explorer before
critic_update_delay = 5 # soft update of critic ~ off-policy, how much fits on explorer before
critic_learn_delta = 5 # here how much episodes before critic(and therefore also actor)-explorer update

# usually when we normalize advantages, we want to use sum in PG, and also attention is preferred
pg_mean = true#false#

good_reach = 2 # select from experience only related things if task is designed that way
advantages_enabled = true#false#
advantages_boost = true#false#
normalize_advantages = false#true#

attention_enabled = false#true#
attention_hidden = 24
attention_amplifier = 1.0

max_n_step = -10000#1#

# scheduling of replay buffer randomnes
replay_alpha = 1.0
replay_beta_iters = 6000 # here we should have enough experience to do serious prioritzation
replay_beta_base = 0.2
replay_beta_top = 0.7
replay_prio_eps = 1e-10

#####################################
# neural nets settings
#####################################

#lstm advancement
history_count = 3
history_features = 64

her_state_size = 0
her_state_features = 0
her_max_ratio = 0

dbgout_train = false#true#
fast_exp_epochs = 4
ppo_eps = 2e-1
loss_min = 1000

dbgout_ratio = true#false#
ddpg = false#true#

replay_cleaning = true#false#
prob_treshold = 3.0

gae = true#false#
gae_tau = 0.95

replay_reanalyze = true#false#
