#####################################
# Most common to tune
#####################################

ddpg = false#true#
gae = true#false#

n_step = 1
batch_size = 1
discount_rate = 0.995
n_simulations = 6
n_critics = 1
disjoint_critics = false

critic_learn_delta = 5

lr_actor = 3e-4
lr_critic = 1e-4

mcts_rounds = 1 # in reacher it indicates only how often it will be rendered for test

max_n_episode = 70
max_ep_draw_count = 1

target_future_features = true#false#
detach_eval = true#false#
detached_actor = false#true#

#####################################
# neural nets settings
#####################################

use_batch_norm = false#true#
use_curiosity_buf = false#true#

history_count = 4
history_features = 128

her_state_size = 3
her_state_features = 32

#####################################
# PG algorithm settings
#####################################

postpone_exploring_while_learning = true#false#
fast_exp_epochs = 4
ppo_eps = 2e-1
loss_min = 1000

gae_tau = 0.95

#####################################
# replay buffer
#####################################

replay_size = 310 # last 3 eps

her_max_ratio = 5

replay_reanalyze = true#false#
replay_cleaning = true#false#
prob_treshold = 3.0

replay_alpha = 0.7
replay_beta_iters = 6000
replay_beta_base = 0.2
replay_beta_top = 0.8
replay_prio_eps = 1e-16

#####################################
# Quirks ~ related to gradients +-
#####################################

pg_mean = true#false#
action_repeat = 1#2#

good_reach = 1
advantages_enabled = true#false#
advantages_boost = false#true#
normalize_advantages = false#true#

attention_enabled = false#true#
attention_hidden = 64
attention_amplifier = 2.0

# reinforce or TD-lambda
td_lambda_replay_count = 0
reinforce_clip = false
tau_clip = 0

mcts_random_cap = 1000000

#####################################
# Learning rates hyper params
#####################################

actor_update_delay = 3
critic_update_delay = 3

tau_base = 5e-1
tau_final = 1e-2
tau_replay_counter = 10000

#####################################
# debug and visuals
#####################################

max_n_step = 1#-10000#

dbgout_train = false#true#
dbgout_ratio = false#true#
dbgout = false#true#
loss_debug = false#true

#####################################
# MODEL specifics
#####################################

device = "cpu"#"cuda"#
tensor = "torch.DoubleTensor"#"torch.cuda.DoubleTensor"#
model_path = "reacher_her_dtb"
load = true#false#
save = true#false#
